# Generated by Django 4.1.3 on 2022-11-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='avaliacao',
        ),
    ]
