# Generated by Django 4.1.3 on 2022-11-27 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cliente_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nota',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Nota'),
        ),
    ]
